### Afstande mellem ord. {#afstande-mellem-ord. .unnumbered}

Et ord er en følge eller en *streng* af bogstaver eller tal *hnaikgoh*
(nej, det behøver ikke give mening). Det kunne være en DNA-sekvens, et
ord i en tekst eller noget helt andet [^1] Længden af en streng er
antallet af bogstaver. *Edit-afstande* er basalt set, hvor mange
ændringer, man skal lave, for at komme fra den ene streng til den anden.
Det afhænger naturligvis af, hvilke typer ændringer, man tillader.

-   Hammingafstanden mellem to lige lange strenge er Antallet af
    pladser, hvor de to strenge er forskellige. Afstand fra *sne* til
    *sno* er $1$. Afstand fra *sne* til *neg* er $3$. Det svarer til, at
    man må ændre et bogstav ad gangen. *sne* $\rightarrow$ *nne*
    $\rightarrow$ *nee* $\rightarrow$ *neg*.

-   Levenshteinafstanden har flere tilladte ændringer: Man må ændre
    bogstaver, som i Hamming, men man må også indsætte og fjerne
    bogstaver. Levenshteinfstanden er det mindste antal sådanne
    ændringer, man skal lave for at nå fra det ene ord til det andet.
    Ordene/strengene behøver ikke have samme længde - man kan jo
    indsætte og fjerne bogstaver.

    -   Afstand fra *sne* til *sno* er $1$, ligesom Hammingafstanden.

    -   Afstand fra *sne* til *sned* er også $1$ - og her er
        Hammingafstanden slet ikke meningsfuld. Den er ikke defineret.

    -   Afstand fra *sne* til *neg* er $2$ - via disse ændringer: *sne*
        $\rightarrow$ *ne*$\rightarrow$ *neg*. Hammingafstanden er 3.

    Jo flere tilladte ændringer, jo kortere afstand. Der er algoritmer,
    der finder denne mindste vej mellem to ord - det er ikke helt så
    klart, hvordan man regner den ud, som for Hammingafstanden. Bemærk,
    at vi kunne have valgt *sne* $\rightarrow$ *sneg*$\rightarrow$
    *neg*, som også har to \"moves\".

-   Damerau-Levenshteinafstanden er som Levenshtein, men man tillader nu
    også ombytning af to bogstaver, som står ved siden af hinanden. Hvis
    man skriver teskt på en telefon eller pc, er det let at bytte om på
    den måde. Hvis man så har en liste over ord, der giver mening, kan
    man opdage, at teskt ikke giver mening, men at ordet tekst ligger
    meget tæt på - afstand 1 i dette afstandsmål - afstand 2 i Hamming
    eller Levenshtein. Ordet teske har også Hammingafstand 1 til teskt,
    så man kan ikke være sikker på, hvad det oprindelige var.

FIGUR: Graf med ord i hver knude og kanter svarende til edit moves.
Måske interaktivt, så man kan se, at kanter forsvinder, hvis man går fra
Levenshtein til Hamming. Afstand mellem DNA-strenge kan man se på med
edit-afstande. Så det er bestemt ikke kun ord i sædvanlig forstand.

Afstande mellem navne: Navne som Peter, Pieter, Pietro, Petrus, Peder,
Per, Pelle, Pekka, Peer, Petur, Pedro, Pierre, Pjotr, Pyotr, Petar eller
måske Katarina, Katharina, Katrina, Katrine, Katrin, Cathryn, Kathryn,
Catherine har samme oprindelse. Der er stor forskel på, hvor hyppigt, de
optræder i forskellige lande. Overvej, om metrikkerne ovenfor kan bruges
til at afsløre, hvor tæt på hinanden lande med Peter som hyppigst, er på
lande med Pyotr.

[^1]: Ofte gør man det desuden binært, så det er en streng af $0$ og $1$
    såsom $00110110$ Det er fornuftigt nok, eftersom computere opererer
    med den slags strenge.
