project:
  type: website
  resources: 
    - "*.ggb"
    - "*.xlsx"
    - "*.zip"

website:
    title: "AI - Aalborg Intelligence - OLD VERSION!"
  description: "Gymnasieundervisning i kunstig intelligens"
  navbar:
    right:
      - text: "Om os"
        href: about.qmd
    left:
      - text: "Undervisningsforløb"
        href: undervisningsforlob.qmd
      - text: "SRO"
        href: sro.qmd
      - text: "SRP"
        href: srp.qmd
      - text: "Materialer"
        href: materialer.qmd
      - text: "Apps"
        href: apps.qmd
      - text: "Referencer"
        href: referencer.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
